### ISSUE TITLE
Add new layout features

### ISSUE THREAD

**Issue by nikoBrajdic** [TwoSpookyBoos/IdleOnAutoReviewBot#11]
* Some kind of banner for icons. I don't care too much if it is top or bottom
* A way to detect system/OS/Browser settings for the light and dark mode, instead of just defaulting dark
  * [possible solution](https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers)
* Create a sidebar for page info and player search
  * `<aside>`
* The third idea was making each section collapsable. Original idea there was almost like a table, with image on left and text on right. Just collapsable in general
  ![section example](https://media.discordapp.net/attachments/1175531106607579237/1187807450309603408/image.png?ex=65983ae4&is=6585c5e4&hm=c1ea268a4041ab5bca04e102e05629fc4148c20cca55b1ed40a5b4fc1d35b7e0&=&format=webp&quality=lossless&width=376&height=468)

**Comment by TwoSpookyBoos** [comment]
Should have been closed with https://github.com/TwoSpookyBoos/IdleOnAutoReviewBot/commit/1005e1f688d0893654b872ee18dfdab0d053a1b8 oops
